/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../../routes/__root'
import { Route as TestQueryRouteImport } from './../../routes/test-query'
import { Route as PublicRouteRouteImport } from './../../routes/_public/route'
import { Route as AuthedRouteRouteImport } from './../../routes/_authed/route'
import { Route as PublicIndexRouteImport } from './../../routes/_public/index'
import { Route as DevEmailsRouteImport } from './../../routes/dev/emails'
import { Route as PublicTermsRouteImport } from './../../routes/_public/terms'
import { Route as PublicSubProcessorsRouteImport } from './../../routes/_public/sub-processors'
import { Route as PublicStripeDisputeEvidenceRouteImport } from './../../routes/_public/stripe-dispute-evidence'
import { Route as PublicSignInRouteImport } from './../../routes/_public/sign-in'
import { Route as PublicPrivacyRouteImport } from './../../routes/_public/privacy'
import { Route as AuthedSetupRouteImport } from './../../routes/_authed/setup'
import { Route as AuthedSettingsRouteImport } from './../../routes/_authed/settings'
import { Route as AuthedDisputesRouteImport } from './../../routes/_authed/disputes'
import { Route as AuthedDashboardRouteImport } from './../../routes/_authed/dashboard'
import { Route as AuthedBillingRouteImport } from './../../routes/_authed/billing'
import { Route as AuthedAccountRouteImport } from './../../routes/_authed/account'
import { Route as ApiStripeWebhookRouteImport } from './../../routes/api/stripe/webhook'
import { Route as ApiCacheImagesRouteImport } from './../../routes/api/cache/images'
import { Route as ApiAuthSplatRouteImport } from './../../routes/api/auth/$'
import { Route as AuthedDisputesDisputeIdRouteImport } from './../../routes/_authed/disputes.$disputeId'
import { Route as ApiStripeOauthCallbackRouteImport } from './../../routes/api/stripe/oauth/callback'

const TestQueryRoute = TestQueryRouteImport.update({
  id: '/test-query',
  path: '/test-query',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const DevEmailsRoute = DevEmailsRouteImport.update({
  id: '/dev/emails',
  path: '/dev/emails',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicTermsRoute = PublicTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicSubProcessorsRoute = PublicSubProcessorsRouteImport.update({
  id: '/sub-processors',
  path: '/sub-processors',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicStripeDisputeEvidenceRoute =
  PublicStripeDisputeEvidenceRouteImport.update({
    id: '/stripe-dispute-evidence',
    path: '/stripe-dispute-evidence',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const PublicSignInRoute = PublicSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicPrivacyRoute = PublicPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthedSetupRoute = AuthedSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedDisputesRoute = AuthedDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedBillingRoute = AuthedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAccountRoute = AuthedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCacheImagesRoute = ApiCacheImagesRouteImport.update({
  id: '/api/cache/images',
  path: '/api/cache/images',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDisputesDisputeIdRoute = AuthedDisputesDisputeIdRouteImport.update({
  id: '/$disputeId',
  path: '/$disputeId',
  getParentRoute: () => AuthedDisputesRoute,
} as any)
const ApiStripeOauthCallbackRoute = ApiStripeOauthCallbackRouteImport.update({
  id: '/api/stripe/oauth/callback',
  path: '/api/stripe/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/test-query': typeof TestQueryRoute
  '/account': typeof AuthedAccountRoute
  '/billing': typeof AuthedBillingRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/disputes': typeof AuthedDisputesRouteWithChildren
  '/settings': typeof AuthedSettingsRoute
  '/setup': typeof AuthedSetupRoute
  '/privacy': typeof PublicPrivacyRoute
  '/sign-in': typeof PublicSignInRoute
  '/stripe-dispute-evidence': typeof PublicStripeDisputeEvidenceRoute
  '/sub-processors': typeof PublicSubProcessorsRoute
  '/terms': typeof PublicTermsRoute
  '/dev/emails': typeof DevEmailsRoute
  '/disputes/$disputeId': typeof AuthedDisputesDisputeIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cache/images': typeof ApiCacheImagesRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/stripe/oauth/callback': typeof ApiStripeOauthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/test-query': typeof TestQueryRoute
  '/account': typeof AuthedAccountRoute
  '/billing': typeof AuthedBillingRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/disputes': typeof AuthedDisputesRouteWithChildren
  '/settings': typeof AuthedSettingsRoute
  '/setup': typeof AuthedSetupRoute
  '/privacy': typeof PublicPrivacyRoute
  '/sign-in': typeof PublicSignInRoute
  '/stripe-dispute-evidence': typeof PublicStripeDisputeEvidenceRoute
  '/sub-processors': typeof PublicSubProcessorsRoute
  '/terms': typeof PublicTermsRoute
  '/dev/emails': typeof DevEmailsRoute
  '/disputes/$disputeId': typeof AuthedDisputesDisputeIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cache/images': typeof ApiCacheImagesRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/stripe/oauth/callback': typeof ApiStripeOauthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/test-query': typeof TestQueryRoute
  '/_authed/account': typeof AuthedAccountRoute
  '/_authed/billing': typeof AuthedBillingRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/disputes': typeof AuthedDisputesRouteWithChildren
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/setup': typeof AuthedSetupRoute
  '/_public/privacy': typeof PublicPrivacyRoute
  '/_public/sign-in': typeof PublicSignInRoute
  '/_public/stripe-dispute-evidence': typeof PublicStripeDisputeEvidenceRoute
  '/_public/sub-processors': typeof PublicSubProcessorsRoute
  '/_public/terms': typeof PublicTermsRoute
  '/dev/emails': typeof DevEmailsRoute
  '/_public/': typeof PublicIndexRoute
  '/_authed/disputes/$disputeId': typeof AuthedDisputesDisputeIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cache/images': typeof ApiCacheImagesRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/stripe/oauth/callback': typeof ApiStripeOauthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/test-query'
    | '/account'
    | '/billing'
    | '/dashboard'
    | '/disputes'
    | '/settings'
    | '/setup'
    | '/privacy'
    | '/sign-in'
    | '/stripe-dispute-evidence'
    | '/sub-processors'
    | '/terms'
    | '/dev/emails'
    | '/disputes/$disputeId'
    | '/api/auth/$'
    | '/api/cache/images'
    | '/api/stripe/webhook'
    | '/api/stripe/oauth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/test-query'
    | '/account'
    | '/billing'
    | '/dashboard'
    | '/disputes'
    | '/settings'
    | '/setup'
    | '/privacy'
    | '/sign-in'
    | '/stripe-dispute-evidence'
    | '/sub-processors'
    | '/terms'
    | '/dev/emails'
    | '/disputes/$disputeId'
    | '/api/auth/$'
    | '/api/cache/images'
    | '/api/stripe/webhook'
    | '/api/stripe/oauth/callback'
  id:
    | '__root__'
    | '/_authed'
    | '/_public'
    | '/test-query'
    | '/_authed/account'
    | '/_authed/billing'
    | '/_authed/dashboard'
    | '/_authed/disputes'
    | '/_authed/settings'
    | '/_authed/setup'
    | '/_public/privacy'
    | '/_public/sign-in'
    | '/_public/stripe-dispute-evidence'
    | '/_public/sub-processors'
    | '/_public/terms'
    | '/dev/emails'
    | '/_public/'
    | '/_authed/disputes/$disputeId'
    | '/api/auth/$'
    | '/api/cache/images'
    | '/api/stripe/webhook'
    | '/api/stripe/oauth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  TestQueryRoute: typeof TestQueryRoute
  DevEmailsRoute: typeof DevEmailsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCacheImagesRoute: typeof ApiCacheImagesRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiStripeOauthCallbackRoute: typeof ApiStripeOauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-query': {
      id: '/test-query'
      path: '/test-query'
      fullPath: '/test-query'
      preLoaderRoute: typeof TestQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/dev/emails': {
      id: '/dev/emails'
      path: '/dev/emails'
      fullPath: '/dev/emails'
      preLoaderRoute: typeof DevEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/terms': {
      id: '/_public/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PublicTermsRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/sub-processors': {
      id: '/_public/sub-processors'
      path: '/sub-processors'
      fullPath: '/sub-processors'
      preLoaderRoute: typeof PublicSubProcessorsRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/stripe-dispute-evidence': {
      id: '/_public/stripe-dispute-evidence'
      path: '/stripe-dispute-evidence'
      fullPath: '/stripe-dispute-evidence'
      preLoaderRoute: typeof PublicStripeDisputeEvidenceRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/sign-in': {
      id: '/_public/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof PublicSignInRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/privacy': {
      id: '/_public/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PublicPrivacyRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_authed/setup': {
      id: '/_authed/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthedSetupRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/disputes': {
      id: '/_authed/disputes'
      path: '/disputes'
      fullPath: '/disputes'
      preLoaderRoute: typeof AuthedDisputesRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/billing': {
      id: '/_authed/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthedBillingRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/account': {
      id: '/_authed/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthedAccountRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cache/images': {
      id: '/api/cache/images'
      path: '/api/cache/images'
      fullPath: '/api/cache/images'
      preLoaderRoute: typeof ApiCacheImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/disputes/$disputeId': {
      id: '/_authed/disputes/$disputeId'
      path: '/$disputeId'
      fullPath: '/disputes/$disputeId'
      preLoaderRoute: typeof AuthedDisputesDisputeIdRouteImport
      parentRoute: typeof AuthedDisputesRoute
    }
    '/api/stripe/oauth/callback': {
      id: '/api/stripe/oauth/callback'
      path: '/api/stripe/oauth/callback'
      fullPath: '/api/stripe/oauth/callback'
      preLoaderRoute: typeof ApiStripeOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedDisputesRouteChildren {
  AuthedDisputesDisputeIdRoute: typeof AuthedDisputesDisputeIdRoute
}

const AuthedDisputesRouteChildren: AuthedDisputesRouteChildren = {
  AuthedDisputesDisputeIdRoute: AuthedDisputesDisputeIdRoute,
}

const AuthedDisputesRouteWithChildren = AuthedDisputesRoute._addFileChildren(
  AuthedDisputesRouteChildren,
)

interface AuthedRouteRouteChildren {
  AuthedAccountRoute: typeof AuthedAccountRoute
  AuthedBillingRoute: typeof AuthedBillingRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedDisputesRoute: typeof AuthedDisputesRouteWithChildren
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedSetupRoute: typeof AuthedSetupRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedAccountRoute: AuthedAccountRoute,
  AuthedBillingRoute: AuthedBillingRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedDisputesRoute: AuthedDisputesRouteWithChildren,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedSetupRoute: AuthedSetupRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicPrivacyRoute: typeof PublicPrivacyRoute
  PublicSignInRoute: typeof PublicSignInRoute
  PublicStripeDisputeEvidenceRoute: typeof PublicStripeDisputeEvidenceRoute
  PublicSubProcessorsRoute: typeof PublicSubProcessorsRoute
  PublicTermsRoute: typeof PublicTermsRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicPrivacyRoute: PublicPrivacyRoute,
  PublicSignInRoute: PublicSignInRoute,
  PublicStripeDisputeEvidenceRoute: PublicStripeDisputeEvidenceRoute,
  PublicSubProcessorsRoute: PublicSubProcessorsRoute,
  PublicTermsRoute: PublicTermsRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  TestQueryRoute: TestQueryRoute,
  DevEmailsRoute: DevEmailsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCacheImagesRoute: ApiCacheImagesRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiStripeOauthCallbackRoute: ApiStripeOauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from '../../start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
