/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../../routes/__root'
import { Route as SitemapDotxmlRouteImport } from './../../routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './../../routes/robots[.]txt'
import { Route as DevRouteRouteImport } from './../../routes/dev/route'
import { Route as PublicRouteRouteImport } from './../../routes/_public/route'
import { Route as AuthedRouteRouteImport } from './../../routes/_authed/route'
import { Route as DevIndexRouteImport } from './../../routes/dev/index'
import { Route as PublicIndexRouteImport } from './../../routes/_public/index'
import { Route as DevEvidencePacketsRouteImport } from './../../routes/dev/evidence-packets'
import { Route as DevEmailsRouteImport } from './../../routes/dev/emails'
import { Route as PublicTermsRouteImport } from './../../routes/_public/terms'
import { Route as PublicSubProcessorsRouteImport } from './../../routes/_public/sub-processors'
import { Route as PublicSignInRouteImport } from './../../routes/_public/sign-in'
import { Route as PublicPrivacyRouteImport } from './../../routes/_public/privacy'
import { Route as AuthedSetupRouteImport } from './../../routes/_authed/setup'
import { Route as AuthedNotificationsRouteImport } from './../../routes/_authed/notifications'
import { Route as AuthedBillingRouteImport } from './../../routes/_authed/billing'
import { Route as AuthedAccountRouteImport } from './../../routes/_authed/account'
import { Route as DevEmailsIndexRouteImport } from './../../routes/dev/emails/index'
import { Route as AuthedProductsIndexRouteImport } from './../../routes/_authed/products/index'
import { Route as DevEvidencePacketsPdfRouteImport } from './../../routes/dev/evidence-packets/pdf'
import { Route as DevEmailsPreviewRouteImport } from './../../routes/dev/emails/preview'
import { Route as ApiStripeWebhookRouteImport } from './../../routes/api/stripe/webhook'
import { Route as ApiSlackEventsRouteImport } from './../../routes/api/slack/events'
import { Route as ApiCacheImagesRouteImport } from './../../routes/api/cache/images'
import { Route as ApiAuthSplatRouteImport } from './../../routes/api/auth/$'
import { Route as ApiAgentsSplatRouteImport } from './../../routes/api/agents/$'
import { Route as AuthedProductsNewRouteImport } from './../../routes/_authed/products/new'
import { Route as AuthedProductsProductIdRouteRouteImport } from './../../routes/_authed/products/$productId/route'
import { Route as AuthedProductsProductIdIndexRouteImport } from './../../routes/_authed/products/$productId/index'
import { Route as ApiStripeOauthCallbackRouteImport } from './../../routes/api/stripe/oauth/callback'
import { Route as ApiStripeAppSyncRouteImport } from './../../routes/api/stripe/app/sync'
import { Route as ApiStripeAppSettingsRouteImport } from './../../routes/api/stripe/app/settings'
import { Route as ApiSlackOauthCallbackRouteImport } from './../../routes/api/slack/oauth/callback'
import { Route as ApiDevEmailsPreviewRouteImport } from './../../routes/api/dev/emails/preview'
import { Route as AuthedProductsProductIdPlaybookRouteImport } from './../../routes/_authed/products/$productId/playbook'
import { Route as AuthedProductsProductIdGeneralRouteImport } from './../../routes/_authed/products/$productId/general'
import { Route as AuthedProductsProductIdConnectionsRouteImport } from './../../routes/_authed/products/$productId/connections'
import { Route as AuthedProductsProductIdAgentRouteImport } from './../../routes/_authed/products/$productId/agent'
import { Route as AuthedProductsProductIdDisputesIndexRouteImport } from './../../routes/_authed/products/$productId/disputes/index'
import { Route as AuthedProductsProductIdDisputesDisputeIdRouteImport } from './../../routes/_authed/products/$productId/disputes/$disputeId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRouteRoute = DevRouteRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const DevIndexRoute = DevIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DevRouteRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const DevEvidencePacketsRoute = DevEvidencePacketsRouteImport.update({
  id: '/evidence-packets',
  path: '/evidence-packets',
  getParentRoute: () => DevRouteRoute,
} as any)
const DevEmailsRoute = DevEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => DevRouteRoute,
} as any)
const PublicTermsRoute = PublicTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicSubProcessorsRoute = PublicSubProcessorsRouteImport.update({
  id: '/sub-processors',
  path: '/sub-processors',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicSignInRoute = PublicSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicPrivacyRoute = PublicPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthedSetupRoute = AuthedSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedNotificationsRoute = AuthedNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedBillingRoute = AuthedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAccountRoute = AuthedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const DevEmailsIndexRoute = DevEmailsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DevEmailsRoute,
} as any)
const AuthedProductsIndexRoute = AuthedProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const DevEvidencePacketsPdfRoute = DevEvidencePacketsPdfRouteImport.update({
  id: '/pdf',
  path: '/pdf',
  getParentRoute: () => DevEvidencePacketsRoute,
} as any)
const DevEmailsPreviewRoute = DevEmailsPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => DevEmailsRoute,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSlackEventsRoute = ApiSlackEventsRouteImport.update({
  id: '/api/slack/events',
  path: '/api/slack/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCacheImagesRoute = ApiCacheImagesRouteImport.update({
  id: '/api/cache/images',
  path: '/api/cache/images',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsSplatRoute = ApiAgentsSplatRouteImport.update({
  id: '/api/agents/$',
  path: '/api/agents/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedProductsNewRoute = AuthedProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedProductsProductIdRouteRoute =
  AuthedProductsProductIdRouteRouteImport.update({
    id: '/products/$productId',
    path: '/products/$productId',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedProductsProductIdIndexRoute =
  AuthedProductsProductIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedProductsProductIdRouteRoute,
  } as any)
const ApiStripeOauthCallbackRoute = ApiStripeOauthCallbackRouteImport.update({
  id: '/api/stripe/oauth/callback',
  path: '/api/stripe/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeAppSyncRoute = ApiStripeAppSyncRouteImport.update({
  id: '/api/stripe/app/sync',
  path: '/api/stripe/app/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeAppSettingsRoute = ApiStripeAppSettingsRouteImport.update({
  id: '/api/stripe/app/settings',
  path: '/api/stripe/app/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSlackOauthCallbackRoute = ApiSlackOauthCallbackRouteImport.update({
  id: '/api/slack/oauth/callback',
  path: '/api/slack/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevEmailsPreviewRoute = ApiDevEmailsPreviewRouteImport.update({
  id: '/api/dev/emails/preview',
  path: '/api/dev/emails/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedProductsProductIdPlaybookRoute =
  AuthedProductsProductIdPlaybookRouteImport.update({
    id: '/playbook',
    path: '/playbook',
    getParentRoute: () => AuthedProductsProductIdRouteRoute,
  } as any)
const AuthedProductsProductIdGeneralRoute =
  AuthedProductsProductIdGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => AuthedProductsProductIdRouteRoute,
  } as any)
const AuthedProductsProductIdConnectionsRoute =
  AuthedProductsProductIdConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => AuthedProductsProductIdRouteRoute,
  } as any)
const AuthedProductsProductIdAgentRoute =
  AuthedProductsProductIdAgentRouteImport.update({
    id: '/agent',
    path: '/agent',
    getParentRoute: () => AuthedProductsProductIdRouteRoute,
  } as any)
const AuthedProductsProductIdDisputesIndexRoute =
  AuthedProductsProductIdDisputesIndexRouteImport.update({
    id: '/disputes/',
    path: '/disputes/',
    getParentRoute: () => AuthedProductsProductIdRouteRoute,
  } as any)
const AuthedProductsProductIdDisputesDisputeIdRoute =
  AuthedProductsProductIdDisputesDisputeIdRouteImport.update({
    id: '/disputes/$disputeId',
    path: '/disputes/$disputeId',
    getParentRoute: () => AuthedProductsProductIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/dev': typeof DevRouteRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account': typeof AuthedAccountRoute
  '/billing': typeof AuthedBillingRoute
  '/notifications': typeof AuthedNotificationsRoute
  '/setup': typeof AuthedSetupRoute
  '/privacy': typeof PublicPrivacyRoute
  '/sign-in': typeof PublicSignInRoute
  '/sub-processors': typeof PublicSubProcessorsRoute
  '/terms': typeof PublicTermsRoute
  '/dev/emails': typeof DevEmailsRouteWithChildren
  '/dev/evidence-packets': typeof DevEvidencePacketsRouteWithChildren
  '/dev/': typeof DevIndexRoute
  '/products/$productId': typeof AuthedProductsProductIdRouteRouteWithChildren
  '/products/new': typeof AuthedProductsNewRoute
  '/api/agents/$': typeof ApiAgentsSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cache/images': typeof ApiCacheImagesRoute
  '/api/slack/events': typeof ApiSlackEventsRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/dev/emails/preview': typeof DevEmailsPreviewRoute
  '/dev/evidence-packets/pdf': typeof DevEvidencePacketsPdfRoute
  '/products/': typeof AuthedProductsIndexRoute
  '/dev/emails/': typeof DevEmailsIndexRoute
  '/products/$productId/agent': typeof AuthedProductsProductIdAgentRoute
  '/products/$productId/connections': typeof AuthedProductsProductIdConnectionsRoute
  '/products/$productId/general': typeof AuthedProductsProductIdGeneralRoute
  '/products/$productId/playbook': typeof AuthedProductsProductIdPlaybookRoute
  '/api/dev/emails/preview': typeof ApiDevEmailsPreviewRoute
  '/api/slack/oauth/callback': typeof ApiSlackOauthCallbackRoute
  '/api/stripe/app/settings': typeof ApiStripeAppSettingsRoute
  '/api/stripe/app/sync': typeof ApiStripeAppSyncRoute
  '/api/stripe/oauth/callback': typeof ApiStripeOauthCallbackRoute
  '/products/$productId/': typeof AuthedProductsProductIdIndexRoute
  '/products/$productId/disputes/$disputeId': typeof AuthedProductsProductIdDisputesDisputeIdRoute
  '/products/$productId/disputes/': typeof AuthedProductsProductIdDisputesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account': typeof AuthedAccountRoute
  '/billing': typeof AuthedBillingRoute
  '/notifications': typeof AuthedNotificationsRoute
  '/setup': typeof AuthedSetupRoute
  '/privacy': typeof PublicPrivacyRoute
  '/sign-in': typeof PublicSignInRoute
  '/sub-processors': typeof PublicSubProcessorsRoute
  '/terms': typeof PublicTermsRoute
  '/dev/evidence-packets': typeof DevEvidencePacketsRouteWithChildren
  '/dev': typeof DevIndexRoute
  '/products/new': typeof AuthedProductsNewRoute
  '/api/agents/$': typeof ApiAgentsSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cache/images': typeof ApiCacheImagesRoute
  '/api/slack/events': typeof ApiSlackEventsRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/dev/emails/preview': typeof DevEmailsPreviewRoute
  '/dev/evidence-packets/pdf': typeof DevEvidencePacketsPdfRoute
  '/products': typeof AuthedProductsIndexRoute
  '/dev/emails': typeof DevEmailsIndexRoute
  '/products/$productId/agent': typeof AuthedProductsProductIdAgentRoute
  '/products/$productId/connections': typeof AuthedProductsProductIdConnectionsRoute
  '/products/$productId/general': typeof AuthedProductsProductIdGeneralRoute
  '/products/$productId/playbook': typeof AuthedProductsProductIdPlaybookRoute
  '/api/dev/emails/preview': typeof ApiDevEmailsPreviewRoute
  '/api/slack/oauth/callback': typeof ApiSlackOauthCallbackRoute
  '/api/stripe/app/settings': typeof ApiStripeAppSettingsRoute
  '/api/stripe/app/sync': typeof ApiStripeAppSyncRoute
  '/api/stripe/oauth/callback': typeof ApiStripeOauthCallbackRoute
  '/products/$productId': typeof AuthedProductsProductIdIndexRoute
  '/products/$productId/disputes/$disputeId': typeof AuthedProductsProductIdDisputesDisputeIdRoute
  '/products/$productId/disputes': typeof AuthedProductsProductIdDisputesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/dev': typeof DevRouteRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authed/account': typeof AuthedAccountRoute
  '/_authed/billing': typeof AuthedBillingRoute
  '/_authed/notifications': typeof AuthedNotificationsRoute
  '/_authed/setup': typeof AuthedSetupRoute
  '/_public/privacy': typeof PublicPrivacyRoute
  '/_public/sign-in': typeof PublicSignInRoute
  '/_public/sub-processors': typeof PublicSubProcessorsRoute
  '/_public/terms': typeof PublicTermsRoute
  '/dev/emails': typeof DevEmailsRouteWithChildren
  '/dev/evidence-packets': typeof DevEvidencePacketsRouteWithChildren
  '/_public/': typeof PublicIndexRoute
  '/dev/': typeof DevIndexRoute
  '/_authed/products/$productId': typeof AuthedProductsProductIdRouteRouteWithChildren
  '/_authed/products/new': typeof AuthedProductsNewRoute
  '/api/agents/$': typeof ApiAgentsSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cache/images': typeof ApiCacheImagesRoute
  '/api/slack/events': typeof ApiSlackEventsRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/dev/emails/preview': typeof DevEmailsPreviewRoute
  '/dev/evidence-packets/pdf': typeof DevEvidencePacketsPdfRoute
  '/_authed/products/': typeof AuthedProductsIndexRoute
  '/dev/emails/': typeof DevEmailsIndexRoute
  '/_authed/products/$productId/agent': typeof AuthedProductsProductIdAgentRoute
  '/_authed/products/$productId/connections': typeof AuthedProductsProductIdConnectionsRoute
  '/_authed/products/$productId/general': typeof AuthedProductsProductIdGeneralRoute
  '/_authed/products/$productId/playbook': typeof AuthedProductsProductIdPlaybookRoute
  '/api/dev/emails/preview': typeof ApiDevEmailsPreviewRoute
  '/api/slack/oauth/callback': typeof ApiSlackOauthCallbackRoute
  '/api/stripe/app/settings': typeof ApiStripeAppSettingsRoute
  '/api/stripe/app/sync': typeof ApiStripeAppSyncRoute
  '/api/stripe/oauth/callback': typeof ApiStripeOauthCallbackRoute
  '/_authed/products/$productId/': typeof AuthedProductsProductIdIndexRoute
  '/_authed/products/$productId/disputes/$disputeId': typeof AuthedProductsProductIdDisputesDisputeIdRoute
  '/_authed/products/$productId/disputes/': typeof AuthedProductsProductIdDisputesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dev'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/account'
    | '/billing'
    | '/notifications'
    | '/setup'
    | '/privacy'
    | '/sign-in'
    | '/sub-processors'
    | '/terms'
    | '/dev/emails'
    | '/dev/evidence-packets'
    | '/dev/'
    | '/products/$productId'
    | '/products/new'
    | '/api/agents/$'
    | '/api/auth/$'
    | '/api/cache/images'
    | '/api/slack/events'
    | '/api/stripe/webhook'
    | '/dev/emails/preview'
    | '/dev/evidence-packets/pdf'
    | '/products/'
    | '/dev/emails/'
    | '/products/$productId/agent'
    | '/products/$productId/connections'
    | '/products/$productId/general'
    | '/products/$productId/playbook'
    | '/api/dev/emails/preview'
    | '/api/slack/oauth/callback'
    | '/api/stripe/app/settings'
    | '/api/stripe/app/sync'
    | '/api/stripe/oauth/callback'
    | '/products/$productId/'
    | '/products/$productId/disputes/$disputeId'
    | '/products/$productId/disputes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/account'
    | '/billing'
    | '/notifications'
    | '/setup'
    | '/privacy'
    | '/sign-in'
    | '/sub-processors'
    | '/terms'
    | '/dev/evidence-packets'
    | '/dev'
    | '/products/new'
    | '/api/agents/$'
    | '/api/auth/$'
    | '/api/cache/images'
    | '/api/slack/events'
    | '/api/stripe/webhook'
    | '/dev/emails/preview'
    | '/dev/evidence-packets/pdf'
    | '/products'
    | '/dev/emails'
    | '/products/$productId/agent'
    | '/products/$productId/connections'
    | '/products/$productId/general'
    | '/products/$productId/playbook'
    | '/api/dev/emails/preview'
    | '/api/slack/oauth/callback'
    | '/api/stripe/app/settings'
    | '/api/stripe/app/sync'
    | '/api/stripe/oauth/callback'
    | '/products/$productId'
    | '/products/$productId/disputes/$disputeId'
    | '/products/$productId/disputes'
  id:
    | '__root__'
    | '/_authed'
    | '/_public'
    | '/dev'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/_authed/account'
    | '/_authed/billing'
    | '/_authed/notifications'
    | '/_authed/setup'
    | '/_public/privacy'
    | '/_public/sign-in'
    | '/_public/sub-processors'
    | '/_public/terms'
    | '/dev/emails'
    | '/dev/evidence-packets'
    | '/_public/'
    | '/dev/'
    | '/_authed/products/$productId'
    | '/_authed/products/new'
    | '/api/agents/$'
    | '/api/auth/$'
    | '/api/cache/images'
    | '/api/slack/events'
    | '/api/stripe/webhook'
    | '/dev/emails/preview'
    | '/dev/evidence-packets/pdf'
    | '/_authed/products/'
    | '/dev/emails/'
    | '/_authed/products/$productId/agent'
    | '/_authed/products/$productId/connections'
    | '/_authed/products/$productId/general'
    | '/_authed/products/$productId/playbook'
    | '/api/dev/emails/preview'
    | '/api/slack/oauth/callback'
    | '/api/stripe/app/settings'
    | '/api/stripe/app/sync'
    | '/api/stripe/oauth/callback'
    | '/_authed/products/$productId/'
    | '/_authed/products/$productId/disputes/$disputeId'
    | '/_authed/products/$productId/disputes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  DevRouteRoute: typeof DevRouteRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiAgentsSplatRoute: typeof ApiAgentsSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCacheImagesRoute: typeof ApiCacheImagesRoute
  ApiSlackEventsRoute: typeof ApiSlackEventsRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiDevEmailsPreviewRoute: typeof ApiDevEmailsPreviewRoute
  ApiSlackOauthCallbackRoute: typeof ApiSlackOauthCallbackRoute
  ApiStripeAppSettingsRoute: typeof ApiStripeAppSettingsRoute
  ApiStripeAppSyncRoute: typeof ApiStripeAppSyncRoute
  ApiStripeOauthCallbackRoute: typeof ApiStripeOauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/': {
      id: '/dev/'
      path: '/'
      fullPath: '/dev/'
      preLoaderRoute: typeof DevIndexRouteImport
      parentRoute: typeof DevRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/dev/evidence-packets': {
      id: '/dev/evidence-packets'
      path: '/evidence-packets'
      fullPath: '/dev/evidence-packets'
      preLoaderRoute: typeof DevEvidencePacketsRouteImport
      parentRoute: typeof DevRouteRoute
    }
    '/dev/emails': {
      id: '/dev/emails'
      path: '/emails'
      fullPath: '/dev/emails'
      preLoaderRoute: typeof DevEmailsRouteImport
      parentRoute: typeof DevRouteRoute
    }
    '/_public/terms': {
      id: '/_public/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PublicTermsRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/sub-processors': {
      id: '/_public/sub-processors'
      path: '/sub-processors'
      fullPath: '/sub-processors'
      preLoaderRoute: typeof PublicSubProcessorsRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/sign-in': {
      id: '/_public/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof PublicSignInRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/privacy': {
      id: '/_public/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PublicPrivacyRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_authed/setup': {
      id: '/_authed/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthedSetupRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/notifications': {
      id: '/_authed/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthedNotificationsRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/billing': {
      id: '/_authed/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthedBillingRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/account': {
      id: '/_authed/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthedAccountRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/dev/emails/': {
      id: '/dev/emails/'
      path: '/'
      fullPath: '/dev/emails/'
      preLoaderRoute: typeof DevEmailsIndexRouteImport
      parentRoute: typeof DevEmailsRoute
    }
    '/_authed/products/': {
      id: '/_authed/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthedProductsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/dev/evidence-packets/pdf': {
      id: '/dev/evidence-packets/pdf'
      path: '/pdf'
      fullPath: '/dev/evidence-packets/pdf'
      preLoaderRoute: typeof DevEvidencePacketsPdfRouteImport
      parentRoute: typeof DevEvidencePacketsRoute
    }
    '/dev/emails/preview': {
      id: '/dev/emails/preview'
      path: '/preview'
      fullPath: '/dev/emails/preview'
      preLoaderRoute: typeof DevEmailsPreviewRouteImport
      parentRoute: typeof DevEmailsRoute
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/slack/events': {
      id: '/api/slack/events'
      path: '/api/slack/events'
      fullPath: '/api/slack/events'
      preLoaderRoute: typeof ApiSlackEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cache/images': {
      id: '/api/cache/images'
      path: '/api/cache/images'
      fullPath: '/api/cache/images'
      preLoaderRoute: typeof ApiCacheImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/$': {
      id: '/api/agents/$'
      path: '/api/agents/$'
      fullPath: '/api/agents/$'
      preLoaderRoute: typeof ApiAgentsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/products/new': {
      id: '/_authed/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AuthedProductsNewRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/products/$productId': {
      id: '/_authed/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof AuthedProductsProductIdRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/products/$productId/': {
      id: '/_authed/products/$productId/'
      path: '/'
      fullPath: '/products/$productId/'
      preLoaderRoute: typeof AuthedProductsProductIdIndexRouteImport
      parentRoute: typeof AuthedProductsProductIdRouteRoute
    }
    '/api/stripe/oauth/callback': {
      id: '/api/stripe/oauth/callback'
      path: '/api/stripe/oauth/callback'
      fullPath: '/api/stripe/oauth/callback'
      preLoaderRoute: typeof ApiStripeOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/app/sync': {
      id: '/api/stripe/app/sync'
      path: '/api/stripe/app/sync'
      fullPath: '/api/stripe/app/sync'
      preLoaderRoute: typeof ApiStripeAppSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/app/settings': {
      id: '/api/stripe/app/settings'
      path: '/api/stripe/app/settings'
      fullPath: '/api/stripe/app/settings'
      preLoaderRoute: typeof ApiStripeAppSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/slack/oauth/callback': {
      id: '/api/slack/oauth/callback'
      path: '/api/slack/oauth/callback'
      fullPath: '/api/slack/oauth/callback'
      preLoaderRoute: typeof ApiSlackOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dev/emails/preview': {
      id: '/api/dev/emails/preview'
      path: '/api/dev/emails/preview'
      fullPath: '/api/dev/emails/preview'
      preLoaderRoute: typeof ApiDevEmailsPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/products/$productId/playbook': {
      id: '/_authed/products/$productId/playbook'
      path: '/playbook'
      fullPath: '/products/$productId/playbook'
      preLoaderRoute: typeof AuthedProductsProductIdPlaybookRouteImport
      parentRoute: typeof AuthedProductsProductIdRouteRoute
    }
    '/_authed/products/$productId/general': {
      id: '/_authed/products/$productId/general'
      path: '/general'
      fullPath: '/products/$productId/general'
      preLoaderRoute: typeof AuthedProductsProductIdGeneralRouteImport
      parentRoute: typeof AuthedProductsProductIdRouteRoute
    }
    '/_authed/products/$productId/connections': {
      id: '/_authed/products/$productId/connections'
      path: '/connections'
      fullPath: '/products/$productId/connections'
      preLoaderRoute: typeof AuthedProductsProductIdConnectionsRouteImport
      parentRoute: typeof AuthedProductsProductIdRouteRoute
    }
    '/_authed/products/$productId/agent': {
      id: '/_authed/products/$productId/agent'
      path: '/agent'
      fullPath: '/products/$productId/agent'
      preLoaderRoute: typeof AuthedProductsProductIdAgentRouteImport
      parentRoute: typeof AuthedProductsProductIdRouteRoute
    }
    '/_authed/products/$productId/disputes/': {
      id: '/_authed/products/$productId/disputes/'
      path: '/disputes'
      fullPath: '/products/$productId/disputes/'
      preLoaderRoute: typeof AuthedProductsProductIdDisputesIndexRouteImport
      parentRoute: typeof AuthedProductsProductIdRouteRoute
    }
    '/_authed/products/$productId/disputes/$disputeId': {
      id: '/_authed/products/$productId/disputes/$disputeId'
      path: '/disputes/$disputeId'
      fullPath: '/products/$productId/disputes/$disputeId'
      preLoaderRoute: typeof AuthedProductsProductIdDisputesDisputeIdRouteImport
      parentRoute: typeof AuthedProductsProductIdRouteRoute
    }
  }
}

interface AuthedProductsProductIdRouteRouteChildren {
  AuthedProductsProductIdAgentRoute: typeof AuthedProductsProductIdAgentRoute
  AuthedProductsProductIdConnectionsRoute: typeof AuthedProductsProductIdConnectionsRoute
  AuthedProductsProductIdGeneralRoute: typeof AuthedProductsProductIdGeneralRoute
  AuthedProductsProductIdPlaybookRoute: typeof AuthedProductsProductIdPlaybookRoute
  AuthedProductsProductIdIndexRoute: typeof AuthedProductsProductIdIndexRoute
  AuthedProductsProductIdDisputesDisputeIdRoute: typeof AuthedProductsProductIdDisputesDisputeIdRoute
  AuthedProductsProductIdDisputesIndexRoute: typeof AuthedProductsProductIdDisputesIndexRoute
}

const AuthedProductsProductIdRouteRouteChildren: AuthedProductsProductIdRouteRouteChildren =
  {
    AuthedProductsProductIdAgentRoute: AuthedProductsProductIdAgentRoute,
    AuthedProductsProductIdConnectionsRoute:
      AuthedProductsProductIdConnectionsRoute,
    AuthedProductsProductIdGeneralRoute: AuthedProductsProductIdGeneralRoute,
    AuthedProductsProductIdPlaybookRoute: AuthedProductsProductIdPlaybookRoute,
    AuthedProductsProductIdIndexRoute: AuthedProductsProductIdIndexRoute,
    AuthedProductsProductIdDisputesDisputeIdRoute:
      AuthedProductsProductIdDisputesDisputeIdRoute,
    AuthedProductsProductIdDisputesIndexRoute:
      AuthedProductsProductIdDisputesIndexRoute,
  }

const AuthedProductsProductIdRouteRouteWithChildren =
  AuthedProductsProductIdRouteRoute._addFileChildren(
    AuthedProductsProductIdRouteRouteChildren,
  )

interface AuthedRouteRouteChildren {
  AuthedAccountRoute: typeof AuthedAccountRoute
  AuthedBillingRoute: typeof AuthedBillingRoute
  AuthedNotificationsRoute: typeof AuthedNotificationsRoute
  AuthedSetupRoute: typeof AuthedSetupRoute
  AuthedProductsProductIdRouteRoute: typeof AuthedProductsProductIdRouteRouteWithChildren
  AuthedProductsNewRoute: typeof AuthedProductsNewRoute
  AuthedProductsIndexRoute: typeof AuthedProductsIndexRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedAccountRoute: AuthedAccountRoute,
  AuthedBillingRoute: AuthedBillingRoute,
  AuthedNotificationsRoute: AuthedNotificationsRoute,
  AuthedSetupRoute: AuthedSetupRoute,
  AuthedProductsProductIdRouteRoute:
    AuthedProductsProductIdRouteRouteWithChildren,
  AuthedProductsNewRoute: AuthedProductsNewRoute,
  AuthedProductsIndexRoute: AuthedProductsIndexRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicPrivacyRoute: typeof PublicPrivacyRoute
  PublicSignInRoute: typeof PublicSignInRoute
  PublicSubProcessorsRoute: typeof PublicSubProcessorsRoute
  PublicTermsRoute: typeof PublicTermsRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicPrivacyRoute: PublicPrivacyRoute,
  PublicSignInRoute: PublicSignInRoute,
  PublicSubProcessorsRoute: PublicSubProcessorsRoute,
  PublicTermsRoute: PublicTermsRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface DevEmailsRouteChildren {
  DevEmailsPreviewRoute: typeof DevEmailsPreviewRoute
  DevEmailsIndexRoute: typeof DevEmailsIndexRoute
}

const DevEmailsRouteChildren: DevEmailsRouteChildren = {
  DevEmailsPreviewRoute: DevEmailsPreviewRoute,
  DevEmailsIndexRoute: DevEmailsIndexRoute,
}

const DevEmailsRouteWithChildren = DevEmailsRoute._addFileChildren(
  DevEmailsRouteChildren,
)

interface DevEvidencePacketsRouteChildren {
  DevEvidencePacketsPdfRoute: typeof DevEvidencePacketsPdfRoute
}

const DevEvidencePacketsRouteChildren: DevEvidencePacketsRouteChildren = {
  DevEvidencePacketsPdfRoute: DevEvidencePacketsPdfRoute,
}

const DevEvidencePacketsRouteWithChildren =
  DevEvidencePacketsRoute._addFileChildren(DevEvidencePacketsRouteChildren)

interface DevRouteRouteChildren {
  DevEmailsRoute: typeof DevEmailsRouteWithChildren
  DevEvidencePacketsRoute: typeof DevEvidencePacketsRouteWithChildren
  DevIndexRoute: typeof DevIndexRoute
}

const DevRouteRouteChildren: DevRouteRouteChildren = {
  DevEmailsRoute: DevEmailsRouteWithChildren,
  DevEvidencePacketsRoute: DevEvidencePacketsRouteWithChildren,
  DevIndexRoute: DevIndexRoute,
}

const DevRouteRouteWithChildren = DevRouteRoute._addFileChildren(
  DevRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  DevRouteRoute: DevRouteRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiAgentsSplatRoute: ApiAgentsSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCacheImagesRoute: ApiCacheImagesRoute,
  ApiSlackEventsRoute: ApiSlackEventsRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiDevEmailsPreviewRoute: ApiDevEmailsPreviewRoute,
  ApiSlackOauthCallbackRoute: ApiSlackOauthCallbackRoute,
  ApiStripeAppSettingsRoute: ApiStripeAppSettingsRoute,
  ApiStripeAppSyncRoute: ApiStripeAppSyncRoute,
  ApiStripeOauthCallbackRoute: ApiStripeOauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from '../../start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
